# @package _group_
deterministic: false
max_epochs: 601
min_epochs: 1
resume_from_checkpoint: null
check_val_every_n_epoch: 10
num_sanity_val_steps: 0
log_every_n_steps: 8
devices: 1
accelerator: "gpu"
strategy: "ddp"
